### ISSUE TITLE
Running main_backtest.py generates an error

### ISSUE THREAD

**Issue by davidwynter** [tjoignant/Wavelets#2]
```
/home/david/PycharmProjects/Wavelets/functions.py:301: RuntimeWarning: invalid value encountered in true_divide
  density = density_z[:, index] / sum(density_z[:, index])
NB ERROR : 406

WAVELET
Backtesting Results: 0.0%
P-value: 1.0
/home/david/PycharmProjects/Wavelets/orig_backtest.py:126: RuntimeWarning: divide by zero encountered in double_scalars
  sharpe = (annualized_returns - risk_free_rate) / annualized_vol
/home/david/PycharmProjects/Elegant-FinRL/venv/lib/python3.7/site-packages/numpy/core/_methods.py:262: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims, where=where)
/home/david/PycharmProjects/Elegant-FinRL/venv/lib/python3.7/site-packages/numpy/core/_methods.py:222: RuntimeWarning: invalid value encountered in true_divide
  subok=False)
/home/david/PycharmProjects/Elegant-FinRL/venv/lib/python3.7/site-packages/numpy/core/_methods.py:253: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/home/david/PycharmProjects/Wavelets/orig_backtest.py", line 132, in <module>
    [i, j] = functions.compute_MDD(portfolio_value)
  File "/home/david/PycharmProjects/Wavelets/functions.py", line 368, in compute_MDD
    j = np.argmax(X[:i])  # start of period
  File "<__array_function__ internals>", line 6, in argmax
  File "/home/david/PycharmProjects/Elegant-FinRL/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1193, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/home/david/PycharmProjects/Elegant-FinRL/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence
```

**Comment by davidwynter** [comment]
My bad, this was due to my changes
